config/routes.rb
Rails.application.routes.draw do
  resources :favorites

  devise_for :users
  get 'parser/gamebomb'
  get 'parser/show'=> 'parser#show'

  root 'parser#gamebomb'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  require 'rubygems'
  # для получения контента через http
  require 'open-uri'

  # подключаем Nokogiri
  require 'nokogiri'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @favorites = Favorite.all
    respond_with(@favorites)
  end

  def show
    respond_with(@favorite)
  end

  def new
    @favorite = Favorite.new
    respond_with(@favorite)
  end

  def edit
  end

  def create
    @favorite = Favorite.new(favorite_params)
    respond_to do |format|
      if @favorite.save
        format.js
      else
        redirect_to root_path
      end
    end
  end

  def update
    @favorite.update(favorite_params)
    respond_with(@favorite)
  end

  def destroy
    @favorite.destroy
    respond_with(@favorite)
  end

  private
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    def favorite_params
      params[:favorite].permit(:link)
    end
end

app/controllers/parser_controller.rb
class ParserController < ApplicationController

  require 'rubygems'
  # для получения контента через http
  require 'open-uri'

  # подключаем Nokogiri
  require 'nokogiri'

  before_action :include_gamebomb

  def show
    # Parse the URI and retrieve it to a temporary file
    article_tmp_file = open(params[:article_link])

    # Parse the contents of the temporary file as HTML
    @article = Nokogiri::HTML(article_tmp_file)

  end

  def gamebomb
    @favorites = Favorite.all
    # Parse the URI and retrieve it to a temporary file
    news_tmp_file = open('http://gamebomb.ru/')

    # Parse the contents of the temporary file as HTML
    @doc = Nokogiri::HTML(news_tmp_file)

    # @article_link = @doc.css('.items-list .gbnews-listShort a:first').attr('href').text

=begin
    # extract all the categories
    categories = doc.css(main_menu_elements_css_class)



    #html output
    html = ""

    #extract the title from the articles
    categories.each do |category|
      link = category.css(main_menu_links_css_class)

      # since there are multiple titles for each entry on google news
      # for this demo we only want the first (topmost)
      #
      # its very easy to do, since title_nodes is of type NodeSet which implements Enumerable (http://ruby-doc.org/core-2.0.0/Enumerable.html)
      # > title_nodes.class
      #  => Nokogiri::XML::NodeSet
      # > title_nodes.class.ancestors
      #   => [Nokogiri::XML::NodeSet, Enumerable, Object, Kernel, BasicObject]

      ## prime_title = title_nodes.first


      # Even when the css selector returns only one element, its type is also Nokogiri::XML::NodeSet
      ## summary_node = article.css(article_summary_css_class)

      # > summary_node.class
      #  => Nokogiri::XML::NodeSet
      # > summary_node.size
      #  => 1

      # Create an "---------" line for the title
      separator = "-" * link.text.size

      # Extracting the text from an Nokogiri::XML::Element is easy by calling the #text method,
      # notice how we can also do it on the NodeSet,
      # there it as a different semantic by invoking #text in all the children nodes
       html += "%s\n%s" % [link.text, separator]
    end

    #___________________ARTICLES_______________________________

    # extract all the articles
    articles = doc.css(article_css_class)

    #extract the title from the articles
    articles.each do |article|
      article_date = article.css(article_date_css_class)
      article_head = article.css(article_header_css_class)
      article_text = article.css(article_text_css_class)

      # since there are multiple titles for each entry on google news
      # for this demo we only want the first (topmost)
      #
      # its very easy to do, since title_nodes is of type NodeSet which implements Enumerable (http://ruby-doc.org/core-2.0.0/Enumerable.html)
      # > title_nodes.class
      #  => Nokogiri::XML::NodeSet
      # > title_nodes.class.ancestors
      #   => [Nokogiri::XML::NodeSet, Enumerable, Object, Kernel, BasicObject]

      ## prime_title = title_nodes.first


      # Even when the css selector returns only one element, its type is also Nokogiri::XML::NodeSet
      ## summary_node = article.css(article_summary_css_class)

      # > summary_node.class
      #  => Nokogiri::XML::NodeSet
      # > summary_node.size
      #  => 1

      # Create an "---------" line for the title
      separator = "-" * article_head.text.size

      # Extracting the text from an Nokogiri::XML::Element is easy by calling the #text method,
      # notice how we can also do it on the NodeSet,
      # there it as a different semantic by invoking #text in all the children nodes
      html += "\n%s\n%s%s%s\n" % [article_date.text, article_head.text, article_text.text, separator ]
    end

    render :html => html
=end
  end

  private
  def include_gamebomb
    # Parse the URI and retrieve it to a temporary file
    news_tmp_file = open('http://gamebomb.ru/')

    # Parse the contents of the temporary file as HTML
    @doc = Nokogiri::HTML(news_tmp_file)

    # Define the css selectors to be used for extractions, most
    @article_css_class         =".items-list .gbnews-listShort"
    @article_date_css_class    =".sub"
    @article_header_css_class  ="h3"
    @article_text_css_class    ="p"
    @main_menu_elements_css_class ="#header-menu .main-menu li"
    @main_menu_links_css_class ="a"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/parser_helper.rb
module ParserHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Favorites</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/_favorites.html.erb
<ul>
  <% @favorites.each do |favorite| %>
    <li><%= favorite %></li>
  <% end %>
</ul>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <h3><%= link_to 'PARSER', root_path %></h3>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'News', root_path %></li>
        <li><%= link_to 'Favorites', favorites_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to current_user.name, root_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to 'Log in', new_user_session_path %></li>
              <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hakaton</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/header' %>
<div class="container">
  <div class="bs-docs-section">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/parser/gamebomb.html.erb
<div class="row">
  <div class="col-md-9">
    <h1>Listing Topics</h1>
    <table class="table table-striped table-hover ">
      <thead>
      <tr class="info">
        <th>Image</th>
        <th>Title</th>
        <th>DateCreate</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @doc.css(@article_css_class).each do |article| %>
        <% article_link = article.css('.img').attr('href').text %>
        <tr>
          <td style="width: 100px;"><img style="width: 100px;" src="http://gamebomb.ru<%= article.css('img').attr('src').text %>" alt="<%= article.css('img').attr('alt').text %>"></td>
          <td style="max-width: 50px;"><%= link_to article.css(@article_header_css_class).text, parser_show_path(article_link: article_link) %></td>
          <td style="max-width: 50px;"><%= article.css(@article_date_css_class).text %></td>
          <td style="max-width: 50px;"><p><%= article.css(@article_text_css_class).text %></p></td>
          <td><%= link_to 'Add to favorites', controller: 'favorites', action: :create, method: :post, link: article_link %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-3">
    <%= render partial: 'layouts/favorites' %>
  </div>
</div>

app/views/parser/show.html.erb
<div class="well">
  <a href="#" id="styles-change">Click</a>
  <div class="row">
    <div class="col-md-3">
      <img style="width: 200px;" src="http://gamebomb.ru<%= @article.css('.post-content > div:nth-child(3) img').attr('src').text %>" alt="<%= @article.css('.post-content > div:nth-child(3) img').attr('alt').text %>">
    </div>
    <div class="alert alert-dismissible active col-md-9">
      <strong class="lead text-info"><%= @article.css('.post-content h1').text %></strong><hr>
      <small><%= @article.css('.post-content > div:nth-child(2) > div > div').text  %></small>
    </div>
  </div>
  <blockquote>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <p class="tab-content">
          <%= @article.css('.post-content > div:nth-child(3) > div:nth-child(2) p').text %>
        </p>
      </div>
    </div>
  </blockquote>
</div>